import glfw = glfw%lib{glfw}

./: libue{glad_gl}: external/glad/h{gl} external/c{glad_gl}
./: libue{glad_vulkan}: external/glad/h{vulkan} external/c{glad_vulkan}
./: libue{tinycthread}: external/{h c}{tinycthread}
./: libue{getopt}: external/{h c}{getopt}

c.poptions =+ "-I$src_root/external"

# We do not want to provide libraries for every header.
# This makes sure every header is available inside a dist package.
./: external/h{**}

./: tests/ examples/
