import glfw = glfw%lib{glfw}

include ../external/
libs = \
  ../external/libue{glad_gl} \
  ../external/libue{glad_vulkan} \
  ../external/libue{tinycthread} \
  ../external/libue{getopt}

c.poptions =+ "-I$src_base/../external/deps"

if ($c.target.class == 'linux')
{
  c.libs += -lm -pthread
}

for t: c{*}
{
  n = $name($t)
  ./: exe{$n}: $t $glfw $libs: bin.whole = false
}

# exe{glfwinfo}: test = true
