# include ../

if ($c.target.class == 'linux')
{
  c.libs += -lm -pthread
}

for t: c{*}
{
  n = $name($t)
  ./: exe{$n}: $t $glfw ../libue{glad_gl}: bin.whole = false
}

exe{particles}: ../libue{tinycthread} ../libue{getopt}

# exe{*}: test = true
# exe{offscreen}: test = true
